name: .NET CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        env:
          BUILD_CONFIGURATION: Debug
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup .NET Core 6
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '6.0.x'
        - name: Setup .NET Core 8
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
        - name: Test
          run: ./build.sh -target Test