name: NuGet Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup .NET Core 6
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '6.0.x'
        - name: Setup .NET Core 8
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        - name: Test
          run: ./build.sh -target Test
          if: ${{ ! startsWith(github.ref, 'refs/heads/main') }}

        - name: Pack
          run: ./build.sh -target Pack
          if: startsWith(github.ref, 'refs/tags/v')

        - name: Create a release with the NuGet Package
          uses: softprops/action-gh-release@v2
          with:
            files: '**/*.nupkg'
          if: startsWith(github.ref, 'refs/tags/v')

        - name: Load NuGet API Key
          uses: 1password/load-secrets-action@v2
          with:
            export-env: true
          env:
            OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
            NUGET_API_KEY: "op://GitHub Actions/NuGet API Dirt/credential"
          if: startsWith(github.ref, 'refs/tags/v')

        - name: Push NuGet package
          run: ./build.sh -skip Pack -target Publish
          if: startsWith(github.ref, 'refs/tags/v')

