name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: "Restore dotnet tools"
        run: dotnet tool restore
      - uses: pre-commit/action@v3.0.1
